### PR TITLE
Cmake new output

### PR DESCRIPTION
**Pull request by pgrete**
New PR continuing the work in https://github.com/enzo-project/enzo-e/pull/122 just derived to the `new-output` branch and including `ctest`.

I deliberately pushed the changes to a branch in the `enzo-project/enzo-e` git so that everyone can push their changes (such as cmake based machine files) directly without requiring to adjust permission of the involved forks.

At the moment the `ctest` based infrastructure includes just one serial and one parallel test with the intention to use this as a baseline for testing of this PR and collect feedback early on.
The current design runs all test within the build directory (by symlinking the `input` directory) so that the source directory remains clean

Apart from general feedback I'm specifically interested in the following items:
- How should the test results be presented?
  - [ ] When run locally
  - [ ] When run with CI (e.g., do we want to push the results to an overview board like `CDash`, see, e.g., https://my.cdash.org/viewProjects.php)

 `ctest` always displays the results on the terminal (similar to the original `scons` based testing), but the original suite also populated a `php` based overview page. Do we want to keep that kind of overview page? If yes, I suggest to move to a different format, e.g., markdown based (that either be opened directly by a reader) or easily converged (e.g., by `pandoc`) to html, pdf, etc. In other words, remove the dependency on a php installation and/or web server to view the results (if that's already possible then I missed it).

- [ ] Do we still want Flash/swf movies (I vote no, because Flash is EOL)
- [ ] Do we still want gif (I think that'd be useful to keep)
- [ ] Are there other wishes with respect to testing?

### CODE REVIEW

**Comment by mabruzzo** [comment]
> When run with CI (e.g., do we want to push the results to an overview board like CDash, see, e.g., https://my.cdash.org/viewProjects.php)

Out of curiosity, would CI test failures still appear on the PR page? If so, then I don't have a particularly strong feeling.

Naive Question: something like CDash and an overview page seem a little redundant, right? I guess the benefit of the overview page is that we have more control over what it looks like, right? (So it facilitates stuff like embedding images of outputs like James is currently doing).

> but the original suite also populated a php based overview page. Do we want to keep that kind of overview page? If yes, I suggest to move to a different format, e.g., markdown based (that either be opened directly by a reader) or easily converged (e.g., by pandoc) to html, pdf, etc. In other words, remove the dependency on a php installation and/or web server to view the results (if that's already possible then I missed it).

I don't have personally have strong feelings about whether we should populate an overview page.  If we do decide to continue populating an overview page, we may want to think about how easy it is for a contributor to add a test to that page (if we have the page, it should probably be complete).

- under the current system, the procedure for adding a test to the overview page is **very opaque** to me.  As a result, I've just never added any of my tests to that page.
- As you mention, it's also unclear what you need to install to view the results.
- This issue could probably be resolved by documenting the procedure (but currently, my impression is that I would need to learn php to figure it out).

> Are there other wishes with respect to testing?

How easy is it to execute a single test by name with `ctest`? I'd assume that it must be easy, but I figured that I would ask.

For the sake of brainstorming, I figured that I would list 2 more items on my testing "wishlist." I want to preface this by saying that I don't think it's worth the effort for anybody to contemplate either of these objectives until they become necessary (if they ever become necessary). But, I thought that I'd throw these out there. The test suite currently takes a while to complete (20-30 minutes depending on machine). Since the suite will only take longer as additional tests are added, it might be nice to eventually be able to: 
- tag tests as part of a 1 or more `testsets` and be able to easily just execute tests in that `testset`. (If your focusing your efforts within a single component, you only want to run the tests checking that component while you're developing that component)
- run our serial tests in parallel. As things currently stand, the outputs of a simulation in one test could accidentally overwrite the outputs of a simulation in another test, and cause that other test to fail. I had to deal with a variant of this problem while I was writing the ckpt-restart testing script - to robustly address this, we would probably need to be able to sandbox each test to it's own directory...

**Comment by pgrete** [comment]
> > When run with CI (e.g., do we want to push the results to an overview board like CDash, see, e.g., https://my.cdash.org/viewProjects.php)
> 
> Out of curiosity, would CI test failures still appear on the PR page? If so, then I don't have a particularly strong feeling.

Yes, they would because the `ctest` command itself fails if a test fails and the CI infrastructure typically reports the return code of all lines in the CI script.
 
> Naive Question: something like CDash and an overview page seem a little redundant, right? I guess the benefit of the overview page is that we have more control over what it looks like, right? (So it facilitates stuff like embedding images of outputs like James is currently doing).

Kind of yes and no with respect to redundancy. AFAIK CDash would be a central place (e.g., for CI testing) which requires appropriate API token to publish results.
We probably don't want to share those token beyond CI so the question is about how to "publish"/illustrate local test results (e.g., when trying enzo-e on a new machine).
 
> > but the original suite also populated a php based overview page. Do we want to keep that kind of overview page? If yes, I suggest to move to a different format, e.g., markdown based (that either be opened directly by a reader) or easily converged (e.g., by pandoc) to html, pdf, etc. In other words, remove the dependency on a php installation and/or web server to view the results (if that's already possible then I missed it).
> 
> I don't have personally have strong feelings about whether we should populate an overview page. If we do decide to continue populating an overview page, we may want to think about how easy it is for a contributor to add a test to that page (if we have the page, it should probably be complete).

I envision sth very simple, e.g., the markdown document above which can be edited with hard coded path to the desired test outputs (as those won't change typically).

>     * under the current system, the procedure for adding a test to the overview page is **very opaque** to me.  As a result, I've just never added any of my tests to that page.
> 
>     * As you mention, it's also unclear what you need to install to view the results.
> 
>     * This issue could probably be resolved by documenting the procedure (but currently, my impression is that I would need to learn php to figure it out).
> 
> 
> > Are there other wishes with respect to testing?
> 
> How easy is it to execute a single test by name with `ctest`? I'd assume that it must be easy, but I figured that I would ask.

It's straightforward, e.g., by using the full test name as regex `ctest -R mytestname` or by test number `ctest -I S,E` where `S` is the first index to run and `E` the last one (could be identical), see also https://gitlab.kitware.com/cmake/community/-/wikis/doc/ctest/Testing-With-CTest#running-individual-tests

> For the sake of brainstorming, I figured that I would list 2 more items on my testing "wishlist." I want to preface this by saying that I don't think it's worth the effort for anybody to contemplate either of these objectives until they become necessary (if they ever become necessary). But, I thought that I'd throw these out there. The test suite currently takes a while to complete (20-30 minutes depending on machine). Since the suite will only take longer as additional tests are added, it might be nice to eventually be able to:
> 
>     * tag tests as part of a 1 or more `testsets` and be able to easily just execute tests in that `testset`. (If your focusing your efforts within a single component, you only want to run the tests checking that component while you're developing that component)

This is also very straightforward. Each test can be assigned an arbitrary number of labels.
I currently only used `serial` and `parallel` labels, but we could also add labels indicating duration, e.g., `short`, `long`, or by type `unit`, `regression`, .., or component e.g., `mhd`, `hydro`, `amr`, etc.
And then you call `ctest -L regex` to run all test whose labels match regex.
 
>     * run our serial tests in parallel. As things currently stand, the outputs of a simulation in one test could accidentally overwrite the outputs of a simulation in another test, and cause that other test to fail. I had to deal with a variant of this problem while I was writing the ckpt-restart testing script - to robustly address this, we would probably need to be able to sandbox each test to it's own directory...

This should not be possible any more with the suggested structure, because each test will be executed in its own subdirectory (with the `input` directory being linked in).

**Comment by mabruzzo** [comment]
Thanks for taking the time to respond to this. This is all *extremely* cool! I'm definitely sold on this

**Comment by jobordner** [comment]
This looks great! I compiled with cmake and ran ctest with no issues. The local presentation as-is is fine for now, all you really need to know is whether tests pass or not, and ctest handles that nicely enough. I'd concentrate on infrastructure only in this PR and update things just enough to run existing regression tests locally and in circleci. Adding new tests, improving test organization and classification, non-local & graphical presentation of results, etc., can be done in more targeted PR's.

**Comment by pgrete** [comment]
Closing in favor of https://github.com/enzo-project/enzo-e/pull/139

**Pull request closed without merging**
